spring:
  application:
    name: movie-checkr
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/Movie_Checkr
    username: root
    password: Joesph10
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    cors:
      allowed-origins: "*"
      allowed-headers:
        - accept
        - authorization
        - content-type
        - x-requested-with
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
